# Generated by Django 5.2.4 on 2025-07-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
